config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'googlemaps', to: 'pages#google_maps_api'
  get 'managejson', to: 'pages#json'
  get 'list', to: 'users#list', :defaults => { :format => 'json' }

  resources :users, only: [:show, :index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def json
    @users = User.all
    @number = @users.count
    @textblock_ids = []
    @users.each do |u|
      tcount = u.textblocks.count
      i = 0
      tcount.times do |c|
        @textblock_ids << [u.id, i]
        i += 1
      end
    end
    render layout: 'json'
  end

  def google_maps_api
    @users = User.all
    @users_json = @users.to_json
    get_markers
    render layout: 'googlemaps'
  end

  def get_markers # get markers for googlemaps
    @markers = @users.map do |u|
      {
        lng: u.lng,
        lat: u.lat,
        title: "#{u.first_name} #{u.last_name}\n #{u.email}",
        id: u.id
      }
    end
    @markers = @markers.to_json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json, :js

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.js { render json: @users }
    end
  end

  def list
    @list = User.all
    respond_to do |format|
      format.html
      format.json { render json: @list }
    end
  end

  def update
    @user = User.find(params[:id])
    @user.textblocks[params[:index]] = params[:newtext]
    @user.update!(user_params)
    respond_to do |format|
      format.json
      format.html { redirect_back(fallback_location: root_path) }
      # format.js # index.js.erb
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :street_and_number,
      :postalcode,
      :city,
      :phonenumber,
      :lat,
      :lng,
      :textblocks,
      :id
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QEDdev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/googlemaps.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QEDdev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'googlemaps', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_pack_tag 'googlemaps' %>
  </body>
</html>

app/views/layouts/json.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QEDdev Textblocks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'json', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}" %>
    <%= javascript_pack_tag 'json' %>
  </body>
</html>

app/views/pages/google_maps_api.html.erb
<table class="border">
  <tr class="">
    <th>Name</th>
    <th>Phonenumber</th>
    <th>eMail</th>
    <th>Address</th>
    <th>City</th>
  </tr>
  <% @users.each do |u| %>
    <tr class="">
      <td>
        <%= u.last_name  %>, <%= u.first_name %>
      </td>
      <td>
        <%= u.phonenumber %>
      </td>
      <td>
        <%= u.email %>
      </td>
      <td>
        <%= u.street_and_number %>
      </td>
      <td>
        <%= u.city %>
      </td>
      <td>
        <%= u.textblocks %>
      </td>
    </tr>
  <% end %>
</table>
<div>
  <%= @markers %>
</div>
<div class="col-xs-12 col-md-8 googlemap">
  <div id="map" data-markers="<%= @markers %>">
  </div>
</div>
<div>
  <button id="dev2" >Clear</button>
</div>
<a id="kaboom" data-users="<%= @users_json %>" href="#">kaboom</a>

app/views/pages/home.html.erb
<h1>QED Webdevelopment</h1>
<br>
<h2>Development pages:</h2>

<ul>
  <li><%= link_to "Google Maps API", googlemaps_path,  class: "" %></li>
  <li><%= link_to "CRUD json", managejson_path,  class: "" %></li>
  <li>Subject 3</li>
  <li>Subject 4</li>
  <li>Subject 5</li>
  <li>Subject 6</li>
</ul>

app/views/pages/json.html.erb
<h1>QED dev Textblock page</h1>
<span id="data" data-textblock_ids="<%= @textblock_ids %>">text</span>
<p>
  Aantal: <%= @number  %>
</p>

<% @users.each do |u| %>
  <div class="textblocks">
    Textblokken user <%= u.id %>:
    <% @index = u.id * 1000 %>
    <% u.textblocks.each do |t| %>
      <button id="textblock<%= @index %>"> edit textblock<%= @index %> </button>
      <div id="text<%= @index %>" class="textblock">
        <div class="text" >
          textblock<%= @index %> <br>
          <%= t %>
        </div>

      </div>
      <div id="edit<%= @index %>" class="edit-block" style="display: none">
        <input id="new<%= @index %>" type="text" value="<%= t %>">
      </div>
      <% @index += 1 %>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<ul>
<% @users.each do |u| %>
  <li>
    <%= u.first_name %> <%= u.last_name  %>
  </li>
<% end %>
</ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>